/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import SideNavbar from "@/components/SideBar";
import { Toaster } from "@/components/ui/toaster"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning> 
      <body
        className={cn(
          "min-h-screen w-full bg-white text-black flex ",
          inter.className,
          
        )}
      >
       
        <SideNavbar />
        
        <div className="p-8 w-full">
        <Toaster />{children}</div>
      </body>
    </html>
  );
}